- name: Install system packages with apt
  apt:
    name: "{{ item }}"
    update_cache: yes
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ packages }}"

- name: Create neovim autoload directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload"
    state: directory

- name: Install vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim"

- name: Create .config symlink
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    src: "{{ dotfiles }}" 
    state: link

- name: Change shell to zsh
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh

- name: Redirect ZDOTDIR
  copy:
    dest: "{{ lookup('env', 'HOME') }}/.zshenv"
    content: |
      ZDOTDIR=$HOME/.config/zsh

- name: Download oh-my-zsh installer
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh	

- name: Install oh-my-zsh
  script:
    cmd: /tmp/ohmyzsh_install.sh
    creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"

- name: Install antigen
  get_url:
    url: https://git.io/antigen
    dest: "{{ lookup('env', 'HOME') }}/.zsh/antigen.zsh"

- name: Install pure prompt
  git:
    repo: https://github.com/sindresorhus/pure.git
    dest: "{{ lookup('env', 'HOME') }}/.zsh/pure"
