- name: Install system packages with apt
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  become: yes
  become_user: root
  loop: "{{ packages }}"

- name: Install snap packages
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
  become: yes
  become_user: root
  loop: "{{ snap_packages }}"

- name: Create neovim autoload directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    state: directory

- name: Change shell to zsh and generate ssh key
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
    generate_ssh_key: yes

- name: Create config directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item.dest | dirname }}"
    state: directory
  loop: "{{ config_links }}"

- name: Link config files
  file:
    src: "{{ dotfiles }}/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
  loop: "{{ config_links }}"

- name: Install vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"

- name: Install nvim plugins
  shell: nvim --headless +PlugInstall +qall


- name: Redirect ZDOTDIR
  copy:
    dest: "{{ ansible_env.HOME }}/.zshenv"
    content: |
      ZDOTDIR=$HOME/.config/zsh

- name: Install antigen
  get_url:
    url: https://git.io/antigen
    dest: "{{ ansible_env.HOME }}/.config/zsh/antigen.zsh"

- name: Install pure prompt
  git:
    repo: https://github.com/sindresorhus/pure.git
    dest: "{{ ansible_env.HOME }}/.config/zsh/pure"

- name: Install NVM
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install Node.js
  shell: ". {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node"
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node"
    chdir: "{{ ansible_env.HOME }}"
    executable: /bin/bash

- name: Install Claude Code CLI
  shell: ". {{ ansible_env.HOME }}/.nvm/nvm.sh && npm install -g @anthropic-ai/claude"
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node/*/bin/claude"


