- name: Add neovim stable repository from PPA
  become: yes
  become_user: root
  become_method: sudo
  apt_repository:
    repo: ppa:neovim-ppa/stable

- name: Install system packages with apt
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  become: yes
  become_user: root
  loop: "{{ packages }}"

- name: Create neovim autoload directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload"
    state: directory

- name: Install vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim"

- name: Create .config symlink
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    src: "{{ dotfiles }}"
    state: link

- name: Install nvim plugins
  shell: nvim --headless +PlugInstall +qall

- name: Change shell to zsh and generate ssh key
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
    generate_ssh_key: yes

- name: Create .zsh directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.zsh"
    state: directory

- name: Redirect ZDOTDIR
  copy:
    dest: "{{ lookup('env', 'HOME') }}/.zshenv"
    content: |
      ZDOTDIR=$HOME/.config/zsh

- name: Install antigen
  get_url:
    url: https://git.io/antigen
    dest: "{{ lookup('env', 'HOME') }}/.zsh/antigen.zsh"

- name: Install pure prompt
  git:
    repo: https://github.com/sindresorhus/pure.git
    dest: "{{ lookup('env', 'HOME') }}/.zsh/pure"
