# Load antigen packages
source /home/mgouzenko/antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundle git
antigen bundle command-not-found
antigen bundle sudo
antigen bundle battery
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure
antigen bundle web-search
antigen bundle python
antigen bundle zsh-users/zsh-syntax-highlighting
antigen apply

# Prompt
# TODO: Fix this to work with more than 10 jobs
RPROMPT='$(if jobs | wc -l | grep 0 > /dev/null; then : ; else jobs | wc -l | xargs; fi)'

# Environment variables
export MAIL='/var/mail/mgouzenko'
export TERM=xterm-256color

# Aliases
alias ls='ls --color=auto'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias gdb='gdb -q'
alias tunnel='autossh -NT -M 10984 -o "PubkeyAuthentication=yes" -o "PasswordAuthentication=no" -i ~/.ssh/persistent_tunnel -R 6666:localhost:22 root@45.55.202.67'
alias src='source ~/.zshrc'
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
